services:
  rxproduct:
    image: rxproduct:latest
    container_name: rxproduct
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: postgresql

networks:
  app-network:
    external: true